export const classId = state => state.classId
export const buylist = state => state.buylist
export const select = state => state.select
export const price = state => state.price
export const count = state => state.count
export const imgicon = state => state.imgicon
export const address = state => state.address
export const chosenAddressId = state => state.chosenAddressId
export const addressinfo = state => state.addressinfo
export const editChosenAddressId = state => state.editChosenAddressId
export const selectshop = state => state.selectshop